version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '7000:80'
    links:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
  mysql:
    image: mysql:5.7
    volumes:
      - ./runtime/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_USER=kremlin"
      - "MYSQL_DATABASE=kremlin"
    ports:
      - "33063:3306"
    tty: true
